//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("NLG_WI_NationalLifeModel", "FK_srcAgent_AgentProfileId_srcAgentProfile_AgentProfileId", "srcAgentProfile", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DataConnections.srcAgentProfile), "srcAgent", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataConnections.srcAgent), true)]
[assembly: EdmRelationshipAttribute("NLG_WI_NationalLifeModel", "FK_srcAgentProfile_UserProfileId_srcUserProfile_UserProfileId", "srcUserProfile", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DataConnections.srcUserProfile), "srcAgentProfile", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataConnections.srcAgentProfile), true)]

#endregion

namespace DataConnections
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class NLG_WI_NationalLifeEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new NLG_WI_NationalLifeEntities object using the connection string found in the 'NLG_WI_NationalLifeEntities' section of the application configuration file.
        /// </summary>
        public NLG_WI_NationalLifeEntities() : base("name=NLG_WI_NationalLifeEntities", "NLG_WI_NationalLifeEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new NLG_WI_NationalLifeEntities object.
        /// </summary>
        public NLG_WI_NationalLifeEntities(string connectionString) : base(connectionString, "NLG_WI_NationalLifeEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new NLG_WI_NationalLifeEntities object.
        /// </summary>
        public NLG_WI_NationalLifeEntities(EntityConnection connection) : base(connection, "NLG_WI_NationalLifeEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<srcAgent> srcAgents
        {
            get
            {
                if ((_srcAgents == null))
                {
                    _srcAgents = base.CreateObjectSet<srcAgent>("srcAgents");
                }
                return _srcAgents;
            }
        }
        private ObjectSet<srcAgent> _srcAgents;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<srcAgentProfile> srcAgentProfiles
        {
            get
            {
                if ((_srcAgentProfiles == null))
                {
                    _srcAgentProfiles = base.CreateObjectSet<srcAgentProfile>("srcAgentProfiles");
                }
                return _srcAgentProfiles;
            }
        }
        private ObjectSet<srcAgentProfile> _srcAgentProfiles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<srcUserProfile> srcUserProfiles
        {
            get
            {
                if ((_srcUserProfiles == null))
                {
                    _srcUserProfiles = base.CreateObjectSet<srcUserProfile>("srcUserProfiles");
                }
                return _srcUserProfiles;
            }
        }
        private ObjectSet<srcUserProfile> _srcUserProfiles;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the srcAgents EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosrcAgents(srcAgent srcAgent)
        {
            base.AddObject("srcAgents", srcAgent);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the srcAgentProfiles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosrcAgentProfiles(srcAgentProfile srcAgentProfile)
        {
            base.AddObject("srcAgentProfiles", srcAgentProfile);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the srcUserProfiles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosrcUserProfiles(srcUserProfile srcUserProfile)
        {
            base.AddObject("srcUserProfiles", srcUserProfile);
        }

        #endregion
        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="userId">No Metadata Documentation available.</param>
        public ObjectResult<AgentProfileDataSet> usp_GetAgentProfileData(global::System.String userId)
        {
            ObjectParameter userIdParameter;
            if (userId != null)
            {
                userIdParameter = new ObjectParameter("userId", userId);
            }
            else
            {
                userIdParameter = new ObjectParameter("userId", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<AgentProfileDataSet>("usp_GetAgentProfileData", userIdParameter);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NLG_WI_NationalLifeModel", Name="srcAgent")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class srcAgent : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new srcAgent object.
        /// </summary>
        /// <param name="userAgentId">Initial value of the UserAgentId property.</param>
        /// <param name="agentProfileId">Initial value of the AgentProfileId property.</param>
        /// <param name="terminated">Initial value of the Terminated property.</param>
        public static srcAgent CreatesrcAgent(global::System.Int32 userAgentId, global::System.Int64 agentProfileId, global::System.Boolean terminated)
        {
            srcAgent srcAgent = new srcAgent();
            srcAgent.UserAgentId = userAgentId;
            srcAgent.AgentProfileId = agentProfileId;
            srcAgent.Terminated = terminated;
            return srcAgent;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserAgentId
        {
            get
            {
                return _UserAgentId;
            }
            set
            {
                if (_UserAgentId != value)
                {
                    OnUserAgentIdChanging(value);
                    ReportPropertyChanging("UserAgentId");
                    _UserAgentId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UserAgentId");
                    OnUserAgentIdChanged();
                }
            }
        }
        private global::System.Int32 _UserAgentId;
        partial void OnUserAgentIdChanging(global::System.Int32 value);
        partial void OnUserAgentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 AgentProfileId
        {
            get
            {
                return _AgentProfileId;
            }
            set
            {
                OnAgentProfileIdChanging(value);
                ReportPropertyChanging("AgentProfileId");
                _AgentProfileId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AgentProfileId");
                OnAgentProfileIdChanged();
            }
        }
        private global::System.Int64 _AgentProfileId;
        partial void OnAgentProfileIdChanging(global::System.Int64 value);
        partial void OnAgentProfileIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AgentNumber
        {
            get
            {
                return _AgentNumber;
            }
            set
            {
                OnAgentNumberChanging(value);
                ReportPropertyChanging("AgentNumber");
                _AgentNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AgentNumber");
                OnAgentNumberChanged();
            }
        }
        private global::System.String _AgentNumber;
        partial void OnAgentNumberChanging(global::System.String value);
        partial void OnAgentNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Terminated
        {
            get
            {
                return _Terminated;
            }
            set
            {
                OnTerminatedChanging(value);
                ReportPropertyChanging("Terminated");
                _Terminated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Terminated");
                OnTerminatedChanged();
            }
        }
        private global::System.Boolean _Terminated;
        partial void OnTerminatedChanging(global::System.Boolean value);
        partial void OnTerminatedChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NLG_WI_NationalLifeModel", "FK_srcAgent_AgentProfileId_srcAgentProfile_AgentProfileId", "srcAgentProfile")]
        public srcAgentProfile srcAgentProfile
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<srcAgentProfile>("NLG_WI_NationalLifeModel.FK_srcAgent_AgentProfileId_srcAgentProfile_AgentProfileId", "srcAgentProfile").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<srcAgentProfile>("NLG_WI_NationalLifeModel.FK_srcAgent_AgentProfileId_srcAgentProfile_AgentProfileId", "srcAgentProfile").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<srcAgentProfile> srcAgentProfileReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<srcAgentProfile>("NLG_WI_NationalLifeModel.FK_srcAgent_AgentProfileId_srcAgentProfile_AgentProfileId", "srcAgentProfile");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<srcAgentProfile>("NLG_WI_NationalLifeModel.FK_srcAgent_AgentProfileId_srcAgentProfile_AgentProfileId", "srcAgentProfile", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NLG_WI_NationalLifeModel", Name="srcAgentProfile")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class srcAgentProfile : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new srcAgentProfile object.
        /// </summary>
        /// <param name="agentProfileId">Initial value of the AgentProfileId property.</param>
        /// <param name="userProfileId">Initial value of the UserProfileId property.</param>
        /// <param name="primaryAffiliation">Initial value of the PrimaryAffiliation property.</param>
        /// <param name="roleId">Initial value of the RoleId property.</param>
        /// <param name="merrillFlag">Initial value of the MerrillFlag property.</param>
        public static srcAgentProfile CreatesrcAgentProfile(global::System.Int64 agentProfileId, global::System.Int64 userProfileId, global::System.String primaryAffiliation, global::System.Int32 roleId, global::System.Boolean merrillFlag)
        {
            srcAgentProfile srcAgentProfile = new srcAgentProfile();
            srcAgentProfile.AgentProfileId = agentProfileId;
            srcAgentProfile.UserProfileId = userProfileId;
            srcAgentProfile.PrimaryAffiliation = primaryAffiliation;
            srcAgentProfile.RoleId = roleId;
            srcAgentProfile.MerrillFlag = merrillFlag;
            return srcAgentProfile;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 AgentProfileId
        {
            get
            {
                return _AgentProfileId;
            }
            set
            {
                if (_AgentProfileId != value)
                {
                    OnAgentProfileIdChanging(value);
                    ReportPropertyChanging("AgentProfileId");
                    _AgentProfileId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AgentProfileId");
                    OnAgentProfileIdChanged();
                }
            }
        }
        private global::System.Int64 _AgentProfileId;
        partial void OnAgentProfileIdChanging(global::System.Int64 value);
        partial void OnAgentProfileIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 UserProfileId
        {
            get
            {
                return _UserProfileId;
            }
            set
            {
                OnUserProfileIdChanging(value);
                ReportPropertyChanging("UserProfileId");
                _UserProfileId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserProfileId");
                OnUserProfileIdChanged();
            }
        }
        private global::System.Int64 _UserProfileId;
        partial void OnUserProfileIdChanging(global::System.Int64 value);
        partial void OnUserProfileIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PrimaryAffiliation
        {
            get
            {
                return _PrimaryAffiliation;
            }
            set
            {
                OnPrimaryAffiliationChanging(value);
                ReportPropertyChanging("PrimaryAffiliation");
                _PrimaryAffiliation = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PrimaryAffiliation");
                OnPrimaryAffiliationChanged();
            }
        }
        private global::System.String _PrimaryAffiliation;
        partial void OnPrimaryAffiliationChanging(global::System.String value);
        partial void OnPrimaryAffiliationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SecondaryAffiliation
        {
            get
            {
                return _SecondaryAffiliation;
            }
            set
            {
                OnSecondaryAffiliationChanging(value);
                ReportPropertyChanging("SecondaryAffiliation");
                _SecondaryAffiliation = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SecondaryAffiliation");
                OnSecondaryAffiliationChanged();
            }
        }
        private global::System.String _SecondaryAffiliation;
        partial void OnSecondaryAffiliationChanging(global::System.String value);
        partial void OnSecondaryAffiliationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ContractId
        {
            get
            {
                return _ContractId;
            }
            set
            {
                OnContractIdChanging(value);
                ReportPropertyChanging("ContractId");
                _ContractId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ContractId");
                OnContractIdChanged();
            }
        }
        private Nullable<global::System.Int32> _ContractId;
        partial void OnContractIdChanging(Nullable<global::System.Int32> value);
        partial void OnContractIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DistChannelId
        {
            get
            {
                return _DistChannelId;
            }
            set
            {
                OnDistChannelIdChanging(value);
                ReportPropertyChanging("DistChannelId");
                _DistChannelId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DistChannelId");
                OnDistChannelIdChanged();
            }
        }
        private Nullable<global::System.Int32> _DistChannelId;
        partial void OnDistChannelIdChanging(Nullable<global::System.Int32> value);
        partial void OnDistChannelIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RoleId
        {
            get
            {
                return _RoleId;
            }
            set
            {
                OnRoleIdChanging(value);
                ReportPropertyChanging("RoleId");
                _RoleId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RoleId");
                OnRoleIdChanged();
            }
        }
        private global::System.Int32 _RoleId;
        partial void OnRoleIdChanging(global::System.Int32 value);
        partial void OnRoleIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> OffMgrException
        {
            get
            {
                return _OffMgrException;
            }
            set
            {
                OnOffMgrExceptionChanging(value);
                ReportPropertyChanging("OffMgrException");
                _OffMgrException = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OffMgrException");
                OnOffMgrExceptionChanged();
            }
        }
        private Nullable<global::System.Boolean> _OffMgrException;
        partial void OnOffMgrExceptionChanging(Nullable<global::System.Boolean> value);
        partial void OnOffMgrExceptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> AgtAsstException1
        {
            get
            {
                return _AgtAsstException1;
            }
            set
            {
                OnAgtAsstException1Changing(value);
                ReportPropertyChanging("AgtAsstException1");
                _AgtAsstException1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AgtAsstException1");
                OnAgtAsstException1Changed();
            }
        }
        private Nullable<global::System.Boolean> _AgtAsstException1;
        partial void OnAgtAsstException1Changing(Nullable<global::System.Boolean> value);
        partial void OnAgtAsstException1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> AgtAsstException2
        {
            get
            {
                return _AgtAsstException2;
            }
            set
            {
                OnAgtAsstException2Changing(value);
                ReportPropertyChanging("AgtAsstException2");
                _AgtAsstException2 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AgtAsstException2");
                OnAgtAsstException2Changed();
            }
        }
        private Nullable<global::System.Boolean> _AgtAsstException2;
        partial void OnAgtAsstException2Changing(Nullable<global::System.Boolean> value);
        partial void OnAgtAsstException2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> LOA
        {
            get
            {
                return _LOA;
            }
            set
            {
                OnLOAChanging(value);
                ReportPropertyChanging("LOA");
                _LOA = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LOA");
                OnLOAChanged();
            }
        }
        private Nullable<global::System.Boolean> _LOA;
        partial void OnLOAChanging(Nullable<global::System.Boolean> value);
        partial void OnLOAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> DynamicEGAR
        {
            get
            {
                return _DynamicEGAR;
            }
            set
            {
                OnDynamicEGARChanging(value);
                ReportPropertyChanging("DynamicEGAR");
                _DynamicEGAR = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DynamicEGAR");
                OnDynamicEGARChanged();
            }
        }
        private Nullable<global::System.Boolean> _DynamicEGAR;
        partial void OnDynamicEGARChanging(Nullable<global::System.Boolean> value);
        partial void OnDynamicEGARChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ElevatedAgentNumbers
        {
            get
            {
                return _ElevatedAgentNumbers;
            }
            set
            {
                OnElevatedAgentNumbersChanging(value);
                ReportPropertyChanging("ElevatedAgentNumbers");
                _ElevatedAgentNumbers = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ElevatedAgentNumbers");
                OnElevatedAgentNumbersChanged();
            }
        }
        private global::System.String _ElevatedAgentNumbers;
        partial void OnElevatedAgentNumbersChanging(global::System.String value);
        partial void OnElevatedAgentNumbersChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ElevatedRoleId
        {
            get
            {
                return _ElevatedRoleId;
            }
            set
            {
                OnElevatedRoleIdChanging(value);
                ReportPropertyChanging("ElevatedRoleId");
                _ElevatedRoleId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ElevatedRoleId");
                OnElevatedRoleIdChanged();
            }
        }
        private Nullable<global::System.Int32> _ElevatedRoleId;
        partial void OnElevatedRoleIdChanging(Nullable<global::System.Int32> value);
        partial void OnElevatedRoleIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> OnbaseFlag
        {
            get
            {
                return _OnbaseFlag;
            }
            set
            {
                OnOnbaseFlagChanging(value);
                ReportPropertyChanging("OnbaseFlag");
                _OnbaseFlag = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OnbaseFlag");
                OnOnbaseFlagChanged();
            }
        }
        private Nullable<global::System.Boolean> _OnbaseFlag;
        partial void OnOnbaseFlagChanging(Nullable<global::System.Boolean> value);
        partial void OnOnbaseFlagChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean MerrillFlag
        {
            get
            {
                return _MerrillFlag;
            }
            set
            {
                OnMerrillFlagChanging(value);
                ReportPropertyChanging("MerrillFlag");
                _MerrillFlag = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MerrillFlag");
                OnMerrillFlagChanged();
            }
        }
        private global::System.Boolean _MerrillFlag;
        partial void OnMerrillFlagChanging(global::System.Boolean value);
        partial void OnMerrillFlagChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IncentiveFlag
        {
            get
            {
                return _IncentiveFlag;
            }
            set
            {
                OnIncentiveFlagChanging(value);
                ReportPropertyChanging("IncentiveFlag");
                _IncentiveFlag = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IncentiveFlag");
                OnIncentiveFlagChanged();
            }
        }
        private Nullable<global::System.Boolean> _IncentiveFlag;
        partial void OnIncentiveFlagChanging(Nullable<global::System.Boolean> value);
        partial void OnIncentiveFlagChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NLG_WI_NationalLifeModel", "FK_srcAgent_AgentProfileId_srcAgentProfile_AgentProfileId", "srcAgent")]
        public EntityCollection<srcAgent> srcAgents
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<srcAgent>("NLG_WI_NationalLifeModel.FK_srcAgent_AgentProfileId_srcAgentProfile_AgentProfileId", "srcAgent");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<srcAgent>("NLG_WI_NationalLifeModel.FK_srcAgent_AgentProfileId_srcAgentProfile_AgentProfileId", "srcAgent", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NLG_WI_NationalLifeModel", "FK_srcAgentProfile_UserProfileId_srcUserProfile_UserProfileId", "srcUserProfile")]
        public srcUserProfile srcUserProfile
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<srcUserProfile>("NLG_WI_NationalLifeModel.FK_srcAgentProfile_UserProfileId_srcUserProfile_UserProfileId", "srcUserProfile").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<srcUserProfile>("NLG_WI_NationalLifeModel.FK_srcAgentProfile_UserProfileId_srcUserProfile_UserProfileId", "srcUserProfile").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<srcUserProfile> srcUserProfileReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<srcUserProfile>("NLG_WI_NationalLifeModel.FK_srcAgentProfile_UserProfileId_srcUserProfile_UserProfileId", "srcUserProfile");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<srcUserProfile>("NLG_WI_NationalLifeModel.FK_srcAgentProfile_UserProfileId_srcUserProfile_UserProfileId", "srcUserProfile", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NLG_WI_NationalLifeModel", Name="srcUserProfile")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class srcUserProfile : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new srcUserProfile object.
        /// </summary>
        /// <param name="userProfileId">Initial value of the UserProfileId property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="firstName">Initial value of the FirstName property.</param>
        /// <param name="lastName">Initial value of the LastName property.</param>
        /// <param name="userTypeId">Initial value of the UserTypeId property.</param>
        /// <param name="lastModified">Initial value of the LastModified property.</param>
        public static srcUserProfile CreatesrcUserProfile(global::System.Int64 userProfileId, global::System.String userId, global::System.String firstName, global::System.String lastName, global::System.Int32 userTypeId, global::System.DateTime lastModified)
        {
            srcUserProfile srcUserProfile = new srcUserProfile();
            srcUserProfile.UserProfileId = userProfileId;
            srcUserProfile.UserId = userId;
            srcUserProfile.FirstName = firstName;
            srcUserProfile.LastName = lastName;
            srcUserProfile.UserTypeId = userTypeId;
            srcUserProfile.LastModified = lastModified;
            return srcUserProfile;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 UserProfileId
        {
            get
            {
                return _UserProfileId;
            }
            set
            {
                if (_UserProfileId != value)
                {
                    OnUserProfileIdChanging(value);
                    ReportPropertyChanging("UserProfileId");
                    _UserProfileId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UserProfileId");
                    OnUserProfileIdChanged();
                }
            }
        }
        private global::System.Int64 _UserProfileId;
        partial void OnUserProfileIdChanging(global::System.Int64 value);
        partial void OnUserProfileIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.String _UserId;
        partial void OnUserIdChanging(global::System.String value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MiddleIntitial
        {
            get
            {
                return _MiddleIntitial;
            }
            set
            {
                OnMiddleIntitialChanging(value);
                ReportPropertyChanging("MiddleIntitial");
                _MiddleIntitial = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MiddleIntitial");
                OnMiddleIntitialChanged();
            }
        }
        private global::System.String _MiddleIntitial;
        partial void OnMiddleIntitialChanging(global::System.String value);
        partial void OnMiddleIntitialChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CompanyCode
        {
            get
            {
                return _CompanyCode;
            }
            set
            {
                OnCompanyCodeChanging(value);
                ReportPropertyChanging("CompanyCode");
                _CompanyCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CompanyCode");
                OnCompanyCodeChanged();
            }
        }
        private global::System.String _CompanyCode;
        partial void OnCompanyCodeChanging(global::System.String value);
        partial void OnCompanyCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserTypeId
        {
            get
            {
                return _UserTypeId;
            }
            set
            {
                OnUserTypeIdChanging(value);
                ReportPropertyChanging("UserTypeId");
                _UserTypeId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserTypeId");
                OnUserTypeIdChanged();
            }
        }
        private global::System.Int32 _UserTypeId;
        partial void OnUserTypeIdChanging(global::System.Int32 value);
        partial void OnUserTypeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PreferredName
        {
            get
            {
                return _PreferredName;
            }
            set
            {
                OnPreferredNameChanging(value);
                ReportPropertyChanging("PreferredName");
                _PreferredName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PreferredName");
                OnPreferredNameChanged();
            }
        }
        private global::System.String _PreferredName;
        partial void OnPreferredNameChanging(global::System.String value);
        partial void OnPreferredNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address2
        {
            get
            {
                return _Address2;
            }
            set
            {
                OnAddress2Changing(value);
                ReportPropertyChanging("Address2");
                _Address2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address2");
                OnAddress2Changed();
            }
        }
        private global::System.String _Address2;
        partial void OnAddress2Changing(global::System.String value);
        partial void OnAddress2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address3
        {
            get
            {
                return _Address3;
            }
            set
            {
                OnAddress3Changing(value);
                ReportPropertyChanging("Address3");
                _Address3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address3");
                OnAddress3Changed();
            }
        }
        private global::System.String _Address3;
        partial void OnAddress3Changing(global::System.String value);
        partial void OnAddress3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String State
        {
            get
            {
                return _State;
            }
            set
            {
                OnStateChanging(value);
                ReportPropertyChanging("State");
                _State = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("State");
                OnStateChanged();
            }
        }
        private global::System.String _State;
        partial void OnStateChanging(global::System.String value);
        partial void OnStateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Zipcode
        {
            get
            {
                return _Zipcode;
            }
            set
            {
                OnZipcodeChanging(value);
                ReportPropertyChanging("Zipcode");
                _Zipcode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Zipcode");
                OnZipcodeChanged();
            }
        }
        private global::System.String _Zipcode;
        partial void OnZipcodeChanging(global::System.String value);
        partial void OnZipcodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.String _Phone;
        partial void OnPhoneChanging(global::System.String value);
        partial void OnPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> OnbaseFlag
        {
            get
            {
                return _OnbaseFlag;
            }
            set
            {
                OnOnbaseFlagChanging(value);
                ReportPropertyChanging("OnbaseFlag");
                _OnbaseFlag = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OnbaseFlag");
                OnOnbaseFlagChanged();
            }
        }
        private Nullable<global::System.Boolean> _OnbaseFlag;
        partial void OnOnbaseFlagChanging(Nullable<global::System.Boolean> value);
        partial void OnOnbaseFlagChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LastModified
        {
            get
            {
                return _LastModified;
            }
            set
            {
                OnLastModifiedChanging(value);
                ReportPropertyChanging("LastModified");
                _LastModified = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastModified");
                OnLastModifiedChanged();
            }
        }
        private global::System.DateTime _LastModified;
        partial void OnLastModifiedChanging(global::System.DateTime value);
        partial void OnLastModifiedChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NLG_WI_NationalLifeModel", "FK_srcAgentProfile_UserProfileId_srcUserProfile_UserProfileId", "srcAgentProfile")]
        public EntityCollection<srcAgentProfile> srcAgentProfiles
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<srcAgentProfile>("NLG_WI_NationalLifeModel.FK_srcAgentProfile_UserProfileId_srcUserProfile_UserProfileId", "srcAgentProfile");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<srcAgentProfile>("NLG_WI_NationalLifeModel.FK_srcAgentProfile_UserProfileId_srcUserProfile_UserProfileId", "srcAgentProfile", value);
                }
            }
        }

        #endregion
    }

    #endregion
    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="NLG_WI_NationalLifeModel", Name="AgentProfileDataSet")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class AgentProfileDataSet : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AgentProfileDataSet object.
        /// </summary>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="firstName">Initial value of the FirstName property.</param>
        /// <param name="lastName">Initial value of the LastName property.</param>
        /// <param name="userType">Initial value of the UserType property.</param>
        /// <param name="lastModified">Initial value of the LastModified property.</param>
        public static AgentProfileDataSet CreateAgentProfileDataSet(global::System.String userId, global::System.String firstName, global::System.String lastName, global::System.String userType, global::System.DateTime lastModified)
        {
            AgentProfileDataSet agentProfileDataSet = new AgentProfileDataSet();
            agentProfileDataSet.UserId = userId;
            agentProfileDataSet.FirstName = firstName;
            agentProfileDataSet.LastName = lastName;
            agentProfileDataSet.UserType = userType;
            agentProfileDataSet.LastModified = lastModified;
            return agentProfileDataSet;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.String _UserId;
        partial void OnUserIdChanging(global::System.String value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MiddleIntitial
        {
            get
            {
                return _MiddleIntitial;
            }
            set
            {
                OnMiddleIntitialChanging(value);
                ReportPropertyChanging("MiddleIntitial");
                _MiddleIntitial = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MiddleIntitial");
                OnMiddleIntitialChanged();
            }
        }
        private global::System.String _MiddleIntitial;
        partial void OnMiddleIntitialChanging(global::System.String value);
        partial void OnMiddleIntitialChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CompanyCode
        {
            get
            {
                return _CompanyCode;
            }
            set
            {
                OnCompanyCodeChanging(value);
                ReportPropertyChanging("CompanyCode");
                _CompanyCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CompanyCode");
                OnCompanyCodeChanged();
            }
        }
        private global::System.String _CompanyCode;
        partial void OnCompanyCodeChanging(global::System.String value);
        partial void OnCompanyCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserType
        {
            get
            {
                return _UserType;
            }
            set
            {
                OnUserTypeChanging(value);
                ReportPropertyChanging("UserType");
                _UserType = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserType");
                OnUserTypeChanged();
            }
        }
        private global::System.String _UserType;
        partial void OnUserTypeChanging(global::System.String value);
        partial void OnUserTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PreferredName
        {
            get
            {
                return _PreferredName;
            }
            set
            {
                OnPreferredNameChanging(value);
                ReportPropertyChanging("PreferredName");
                _PreferredName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PreferredName");
                OnPreferredNameChanged();
            }
        }
        private global::System.String _PreferredName;
        partial void OnPreferredNameChanging(global::System.String value);
        partial void OnPreferredNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address2
        {
            get
            {
                return _Address2;
            }
            set
            {
                OnAddress2Changing(value);
                ReportPropertyChanging("Address2");
                _Address2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address2");
                OnAddress2Changed();
            }
        }
        private global::System.String _Address2;
        partial void OnAddress2Changing(global::System.String value);
        partial void OnAddress2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address3
        {
            get
            {
                return _Address3;
            }
            set
            {
                OnAddress3Changing(value);
                ReportPropertyChanging("Address3");
                _Address3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address3");
                OnAddress3Changed();
            }
        }
        private global::System.String _Address3;
        partial void OnAddress3Changing(global::System.String value);
        partial void OnAddress3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String State
        {
            get
            {
                return _State;
            }
            set
            {
                OnStateChanging(value);
                ReportPropertyChanging("State");
                _State = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("State");
                OnStateChanged();
            }
        }
        private global::System.String _State;
        partial void OnStateChanging(global::System.String value);
        partial void OnStateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Zipcode
        {
            get
            {
                return _Zipcode;
            }
            set
            {
                OnZipcodeChanging(value);
                ReportPropertyChanging("Zipcode");
                _Zipcode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Zipcode");
                OnZipcodeChanged();
            }
        }
        private global::System.String _Zipcode;
        partial void OnZipcodeChanging(global::System.String value);
        partial void OnZipcodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.String _Phone;
        partial void OnPhoneChanging(global::System.String value);
        partial void OnPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LastModified
        {
            get
            {
                return _LastModified;
            }
            set
            {
                OnLastModifiedChanging(value);
                ReportPropertyChanging("LastModified");
                _LastModified = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastModified");
                OnLastModifiedChanged();
            }
        }
        private global::System.DateTime _LastModified;
        partial void OnLastModifiedChanging(global::System.DateTime value);
        partial void OnLastModifiedChanged();

        #endregion
    }

    #endregion
    
}
